defaults:
  - default.yaml

watch_model:
  _target_: src.callbacks.wandb_callbacks.WatchModel
  log: "all"
  log_freq: 100

upload_code_as_artifact:
  _target_: src.callbacks.wandb_callbacks.UploadCodeAsArtifact
  code_dir: ${work_dir}/src

upload_models_as_artifact:
  _target_: src.callbacks.wandb_callbacks.UploadModelsAsArtifact
  model_dir: "checkpoints/"
  upload_best_only: False
  name: "roberta-base"
  aliases: ["baseline"]
